_commit: 0.0.72
_src_path: gh:mapp-metabolomics-unit/mapp-repo-copier-template
email: pierre-marie.allard@unifr.ch
github_username: digital-botanical-gardens-initiative
gnps_job_id: ''
mapp_batch: cuso_batch_00001
mapp_batch_description: Untargeted metabolomics of UniFr botanical samples CUSO -
    positive mode
mapp_project: dbgi_project_00002
repository_name: dbgi-metabolomics
target_variable: source_taxon
recorded_setup: true
recorded_repository_name: "dbgi-metabolomics"
recorded_author: "MAPP Metabolomics Unit"
recorder_email: "pierre-marie.allard@unifr.ch"
recorded_github_username: "digital-botanical-gardens-initiative"
recorded_mapp_project: "dbgi_project_00002"
recorded_mapp_batch: "cuso_batch_00001"


